unittests-script: ../../scripts/run_unittests_python.sh
conformance-tests-script: ../../scripts/run_conformance_tests_python.sh
copy-build: true
build-dest: build
verbose: true  # verbose flag, defaults to false if not set
